import { ITaskGroups, ITasks } from "@/utils/types";

export const tasks: ITasks[] = [
  {
    id: 1,
    task: "Morning workout",
    place: "Home",
    icon: "barbell",
    iconColor: "#F87171",
    progress: 80,
    activeStrokeColor: "#F87171",
    inActiveStrokeColor: "#2a1515",
  },
  {
    id: 2,
    task: "Mathematics practice",
    place: "Study desk",
    icon: "calculator",
    iconColor: "#60A5FA",
    progress: 60,
    activeStrokeColor: "#60A5FA",
    inActiveStrokeColor: "#111d2e",
  },
  {
    id: 3,
    task: "Complete science assignment",
    place: "School",
    icon: "flask",
    iconColor: "#34D399",
    progress: 40,
    activeStrokeColor: "#34D399",
    inActiveStrokeColor: "#0d2118",
  },
  {
    id: 4,
    task: "Web development learning",
    place: "Laptop",
    icon: "code-slash",
    iconColor: "#818CF8",
    progress: 70,
    activeStrokeColor: "#818CF8",
    inActiveStrokeColor: "#181825",
  },
  {
    id: 5,
    task: "Read 20 pages",
    place: "Bedroom",
    icon: "book",
    iconColor: "#FBBF24",
    progress: 50,
    activeStrokeColor: "#FBBF24",
    inActiveStrokeColor: "#281e09",
  },
];

export const taskGroups: ITaskGroups[] = [
  {
    id: 1,
    group: "Fitness",
    icon: "barbell",
    iconColor: "#F87171",
    totalTasks: 4,
    progress: 65,
    activeStrokeColor: "#F87171",
    inActiveStrokeColor: "#2a1515",
  },
  {
    id: 2,
    group: "Studies",
    icon: "book",
    iconColor: "#60A5FA",
    totalTasks: 6,
    progress: 55,
    activeStrokeColor: "#60A5FA",
    inActiveStrokeColor: "#111d2e",
  },
  {
    id: 3,
    group: "Assignments",
    icon: "document-text",
    iconColor: "#34D399",
    totalTasks: 3,
    progress: 40,
    activeStrokeColor: "#34D399",
    inActiveStrokeColor: "#0d2118",
  },
  {
    id: 4,
    group: "Coding",
    icon: "code-slash",
    iconColor: "#818CF8",
    totalTasks: 5,
    progress: 70,
    activeStrokeColor: "#818CF8",
    inActiveStrokeColor: "#181825",
  },
  {
    id: 5,
    group: "Reading",
    icon: "book-outline",
    iconColor: "#FBBF24",
    totalTasks: 2,
    progress: 50,
    activeStrokeColor: "#FBBF24",
    inActiveStrokeColor: "#281e09",
  },
  {
    id: 6,
    group: "Daily Routine",
    icon: "time",
    iconColor: "#00eace",
    totalTasks: 7,
    progress: 60,
    activeStrokeColor: "#00eace",
    inActiveStrokeColor: "#042320",
  },
  {
    id: 7,
    group: "Health",
    icon: "heart",
    iconColor: "#F472B6",
    totalTasks: 3,
    progress: 75,
    activeStrokeColor: "#F472B6",
    inActiveStrokeColor: "#271020",
  },
  {
    id: 8,
    group: "Personal Development",
    icon: "trending-up",
    iconColor: "#A78BFA",
    totalTasks: 4,
    progress: 65,
    activeStrokeColor: "#A78BFA",
    inActiveStrokeColor: "#1c1628",
  },
  {
    id: 9,
    group: "Projects",
    icon: "folder",
    iconColor: "#FB923C",
    totalTasks: 3,
    progress: 45,
    activeStrokeColor: "#FB923C",
    inActiveStrokeColor: "#271408",
  },
  {
    id: 10,
    group: "Leisure",
    icon: "game-controller",
    iconColor: "#4ADE80",
    totalTasks: 2,
    progress: 80,
    activeStrokeColor: "#4ADE80",
    inActiveStrokeColor: "#0d2116",
  },
];
